### ISSUE TITLE
[bug] Loading .mkv files doesn't work

### ISSUE THREAD

**Issue by spavikevik** [linuxdeepin/deepin-movie#14]
Whenever I try to load a **.mkv** file, Deepin Movie crashes. 

`Traceback (most recent call last):
  File "/usr/share/deepin-movie/views/subtitles.py", line 207, in set_subtitle_from_movie
    self.file_name = get_subtitle_from_movie(movie_file)[0]
  File "/usr/share/deepin-movie/views/subtitles.py", line 95, in get_subtitle_from_movie
    all_this_ext = glob.glob(try_ext)
  File "/usr/lib/python2.7/glob.py", line 27, in glob
    return list(iglob(pathname))
  File "/usr/lib/python2.7/glob.py", line 63, in iglob
    for dirname in dirs:
  File "/usr/lib/python2.7/glob.py", line 64, in iglob
    for name in glob_in_dir(dirname, basename):
  File "/usr/lib/python2.7/glob.py", line 83, in glob1
    return fnmatch.filter(names, pattern)
  File "/usr/lib/python2.7/fnmatch.py", line 56, in filter
    _cache[pat] = re_pat = re.compile(res)
  File "/usr/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: bad character range
`

**Comment by spavikevik** [comment]
EDIT: It could be the case that other filetypes may fail, given the error I get.

**Comment by BLumia** [comment]
Closed due to the project is no longer maintained, please refer to [the new project](https://github.com/linuxdeepin/deepin-movie-reborn/).
