### ISSUE TITLE
Error in launch

### ISSUE THREAD

**Issue by emulienfou** [linuxdeepin/deepin-movie#17]
Since the latest opened movie with **Deepin Movie** app, I cannot start anymore the application.

Launching with in a terminal using the command: `deepin-movie`, I receive the next errors in my terminal:

``` bash
Traceback (most recent call last):
  File "/usr/share/deepin-movie/utils/config.py", line 307, in f
    return pickle.loads(result)
  File "/usr/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1081, in load_obj
    k = self.marker()
  File "/usr/lib/python2.7/pickle.py", line 880, in marker
    while stack[k] is not mark: k = k-1
IndexError: list index out of range
Aborted
```

Removing my file **config.ini** resolve the problem. I presume there is an option who is causing this error hope this can help you find and fix the bug.

Here is what contain my config file:

``` ini
[Player]
volume = 1.0
muted = False
subtitleHide = False
applyLastClosedSize = False
fullscreenOnOpenFile = False
playOrderType = ORDER_TYPE_PLAYLIST_CYCLE
cleanPlaylistOnOpenNewFile = False
autoPlayFromLast = True
autoPlaySeries = True
showPreview = True
forwardRewindStep = 5.0
multipleProgramsAllowed = False
notificationsEnabled = True
pauseOnMinimized = True

[HotkeysPlay]
hotkeyEnabled = True
togglePlay = Space
forward = Right
backward = Left
toggleFullscreen = Return
togglePlaylist = F3
speedUp = Ctrl+Right
slowDown = Ctrl+Left
restoreSpeed = R

[HotkeysFrameSound]
hotkeyEnabled = True
toggleMiniMode = F2
rotateClockwise = W
rotateAnticlockwise = E
increaseVolume = Up
decreaseVolume = Down
toggleMute = M

[HotkeysSubtitles]
hotkeyEnabled = True
subtitleForward = Shift+Right
subtitleBackward = Shift+Left
subtitleMoveUp = Shift+Up
subtitleMoveDown = Shift+Down

[HotkeysFiles]
hotkeyEnabled = True
openFile = Ctrl+O
playPrevious = PgUp
playNext = PgDown

[Subtitle]
autoLoad = True
fontSize = 20.0
fontFamily = 
fontColor = #ffffff
fontBorderSize = 1.0
fontBorderColor = black
verticalPosition = 0.05
delayStep = 0.5

[Others]
leftClick = True
doubleClick = True
wheel = True
```

Thanks

**Comment by hualet** [comment]
It's not reproducable here.
