### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'hotkeysFrameSoundIncreaseVolume'

### ISSUE THREAD

**Issue by Northest** [linuxdeepin/deepin-movie#26]
![deepinscreenshot_select-area_20170721174321](https://user-images.githubusercontent.com/12845347/28475534-303120d6-6e3c-11e7-9ae9-503f36c45bb4.png)

Terminal output:
]$ deepin-movie 

(python2:5350): Gtk-WARNING **: Tema aygıtı module_path "adwaita" içinde bulunamadı,

(python2:5350): Gtk-WARNING **: Tema aygıtı module_path "adwaita" içinde bulunamadı,
Traceback (most recent call last):
  File "/usr/bin/deepin-movie", line 71, in <module>
    from controllers.menu_controller import MenuController
  File "/usr/share/deepin-movie/controllers/menu_controller.py", line 58, in <module>
    ("_sound_increase", _("Volume Up"), (), (), config.hotkeysFrameSoundIncreaseVolume),
AttributeError: 'Config' object has no attribute 'hotkeysFrameSoundIncreaseVolume'

**Comment by unc926** [comment]
Have same problem for me.

**Comment by ademcal** [comment]
I am living same problem My laptop is with optimus
